export const SKILLS = [
  'JavaScript',
  'React',
  'TypeScript',
  'MongoDB',
  'SQL',
  'Node.js',
  'Express.js',
  'Redux',
  'Jest',
  'Cypress',
  'React Testing Library',
  'GoLang',
  'PHP',
  'Webpack',
  'Kubernetes',
  'Docker',
  'Google Firebase',
  'Google Cloud Firestore',
  'Material UI',
  'Git',
  'HTML/CSS/SASS',
]
